version: "3.9"

services:
  board-redis-srv:
    image: redis:6.2.6-buster
    container_name: board-redis-srv
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - /etc/opt/tk-dashboard/redis-master.conf:/usr/local/etc/redis/redis.conf:ro
      - board-redis-data-vol:/data:rw
    networks:
      - board-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  board-import-app:
    build: board-import-app/.
    image: board-import-app-img
    container_name: board-import-app
    restart: unless-stopped
    depends_on:
      - "board-redis-srv"
    volumes:
      - /etc/opt/tk-dashboard/board.conf:/data/conf/board.conf:ro
    networks:
      - board-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  board-export-app:
    build: board-export-app/.
    image: board-export-app-img
    container_name: board-export-app
    restart: unless-stopped
    depends_on:
      - "board-redis-srv"
    volumes:
      - /etc/opt/tk-dashboard/board.conf:/data/conf/board.conf:ro
    networks:
      - board-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  board-meters-app:
    build: board-meters-app/.
    image: board-meters-app-img
    container_name: board-meters-app
    restart: unless-stopped
    depends_on:
      - "board-redis-srv"
    volumes:
      - /etc/opt/tk-dashboard/board.conf:/data/conf/board.conf:ro
    networks:
      - board-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  board-files-app:
    build: board-files-app/.
    image: board-files-app-img
    container_name: board-files-app
    restart: unless-stopped
    depends_on:
      - "board-redis-srv"
    volumes:
      - /etc/opt/tk-dashboard/board.conf:/data/conf/board.conf:ro
      - /srv/dashboard:/srv/dashboard:rw
    networks:
      - board-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  board-admin-shell:
    build: ../common/board-admin-shell/.
    image: board-admin-shell-img
    container_name: board-admin-shell
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /etc/opt/tk-dashboard:/data/conf:rw
      - /srv/dashboard:/srv/dashboard:rw
    networks:
      - board-net
    logging:
      driver: none

volumes:
  board-redis-data-vol:
    name: board-redis-data-vol

networks:
  board-net:
    name: board-net
