version: "3"

services:
  dash-redis-srv:
    image: redis:6.2.3
    container_name: dash-redis-srv
    restart: unless-stopped
    command: redis-server --save 3600 1
    ports:
      - "6379:6379"
    volumes:
      - dash-redis-data-vol:/data
    networks:
      - dash-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  dash-import-app:
    build: dash-import-app/.
    image: dash-import-app-img
    container_name: dash-import-app
    restart: unless-stopped
    volumes:
      - dash-conf-vol:/data/dashboard-conf-vol
    networks:
      - dash-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  dash-conf-vol:
    external: true
  dash-redis-data-vol:
    external: true

networks:
  dash-net:
    external: true

