version: "3.9"

services:
  board-redis-srv:
    image: redis:6.2.6-buster
    container_name: board-redis-srv
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - /etc/opt/tk-dashboard/redis/redis-slave.conf:/usr/local/etc/redis/redis.conf:ro
      - board-redis-data-vol:/data:rw
    networks:
      - board-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  board-redis-master-tls-cli:
    build:
      context: ./
      dockerfile: common/board-stunnel/Dockerfile
    image: board-stunnel-img
    container_name: board-redis-master-tls-cli
    restart: unless-stopped
    command: stunnel /usr/local/etc/stunnel/redis-messein-s-tls-cli-to-master.conf
    volumes:
      - /etc/opt/tk-dashboard/stunnel/:/usr/local/etc/stunnel/:ro
    networks:
      - board-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  board-admin-shell:
    build:
      context: ./
      dockerfile: common/board-admin-shell/Dockerfile
    image: board-admin-shell-img
    container_name: board-admin-shell
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /etc/opt/tk-dashboard:/data/conf:rw
    networks:
      - board-net
    logging:
      driver: none

volumes:
  board-redis-data-vol:
    name: board-redis-data-vol

networks:
  board-net:
    name: board-net

