version: "3"

services:
  board-redis-srv:
    image: redis:6.2.5
    container_name: board-redis-srv
    restart: unless-stopped
    command: redis-server --save 3600 1
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - board-redis-data-vol:/data:rw
    networks:
      - board-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  board-import-app:
    build: board-import-app/.
    image: board-import-app-img
    container_name: board-import-app
    restart: unless-stopped
    depends_on:
      - "board-redis-srv"
    volumes:
      - /etc/opt/tk-dashboard:/data/conf:ro
    networks:
      - board-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  board-files-app:
    build: board-files-app/.
    image: board-files-app-img
    container_name: board-files-app
    restart: unless-stopped
    depends_on:
      - "board-redis-srv"
    volumes:
      - /etc/opt/tk-dashboard:/data/conf:ro
      - /srv/dashboard:/srv/dashboard:rw
    networks:
      - board-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  board-admin-shell:
    build: ../common/board-admin-shell/.
    image: board-admin-shell-img
    container_name: board-admin-shell
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /etc/opt/tk-dashboard:/data/conf:rw
      - /srv/dashboard:/srv/dashboard:rw
    networks:
      - board-net
    logging:
      driver: none

volumes:
  board-redis-data-vol:
    name: board-redis-data-vol

networks:
  board-net:
    name: board-net
