version: "3"

services:
  board-redis-srv:
    image: redis:6.2.3
    container_name: board-redis-srv
    restart: unless-stopped
    command: redis-server --slaveof board-redis-master-relay 6379 --save 3600 1
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - board-redis-data-vol:/data:rw
    networks:
      - board-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  board-redis-master-relay:
    build: ../common/board-redis-master-relay/.
    image: board-redis-master-relay-img
    container_name: board-redis-master-relay
    restart: unless-stopped
    volumes:
      - /etc/opt/tk-dashboard/dashboard.conf:/data/conf/dashboard.conf:ro
      - /home/pi/.ssh:/root/.ssh:ro
    networks:
      - board-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  board-redis-data-vol:
    name: board-redis-data-vol

networks:
  board-net:
    name: board-net

